// GENERATED by make-snapshot.js on 2026-07-23 — do not edit.
// The exact bytes each iOS app received for every pair (fetched with
// REQUEST_HEADERS from pairs.js). In static mode the app shows these,
// so the comparison stays app-faithful without a server.
window.SNAPSHOT_PAIRS = [
 {
  "config1": "snapshot/pair01-config1.jpg",
  "config2": "snapshot/pair01-config2.jpg"
 },
 {
  "config1": "snapshot/pair02-config1.jpg",
  "config2": "snapshot/pair02-config2.jpg"
 },
 {
  "config1": "snapshot/pair03-config1.jpg",
  "config2": "snapshot/pair03-config2.jpg"
 },
 {
  "config1": "snapshot/pair04-config1.jpg",
  "config2": "snapshot/pair04-config2.jpg"
 },
 {
  "config1": "snapshot/pair05-config1.jpg",
  "config2": "snapshot/pair05-config2.jpg"
 },
 {
  "config1": "snapshot/pair06-config1.jpg",
  "config2": "snapshot/pair06-config2.jpg"
 },
 {
  "config1": "snapshot/pair07-config1.jpg",
  "config2": "snapshot/pair07-config2.jpg"
 },
 {
  "config1": "snapshot/pair08-config1.jpg",
  "config2": "snapshot/pair08-config2.jpg"
 },
 {
  "config1": "snapshot/pair09-config1.jpg",
  "config2": "snapshot/pair09-config2.jpg"
 },
 {
  "config1": "snapshot/pair10-config1.jpg",
  "config2": "snapshot/pair10-config2.jpg"
 },
 {
  "config1": "snapshot/pair11-config1.webp",
  "config2": "snapshot/pair11-config2.jpg"
 },
 {
  "config1": "snapshot/pair12-config1.jpg",
  "config2": "snapshot/pair12-config2.jpg"
 },
 {
  "config1": "snapshot/pair13-config1.webp",
  "config2": "snapshot/pair13-config2.jpg"
 },
 {
  "config1": "snapshot/pair14-config1.webp",
  "config2": "snapshot/pair14-config2.jpg"
 },
 {
  "config1": "snapshot/pair15-config1.webp",
  "config2": "snapshot/pair15-config2.jpg"
 },
 {
  "config1": "snapshot/pair16-config1.jpg",
  "config2": "snapshot/pair16-config2.jpg"
 },
 {
  "config1": "snapshot/pair17-config1.webp",
  "config2": "snapshot/pair17-config2.jpg"
 },
 {
  "config1": "snapshot/pair18-config1.webp",
  "config2": "snapshot/pair18-config2.jpg"
 },
 {
  "config1": "snapshot/pair19-config1.webp",
  "config2": "snapshot/pair19-config2.jpg"
 },
 {
  "config1": "snapshot/pair20-config1.webp",
  "config2": "snapshot/pair20-config2.jpg"
 },
 {
  "config1": "snapshot/pair21-config1.webp",
  "config2": "snapshot/pair21-config2.jpg"
 },
 {
  "config1": "snapshot/pair22-config1.webp",
  "config2": "snapshot/pair22-config2.jpg"
 },
 {
  "config1": "snapshot/pair23-config1.webp",
  "config2": "snapshot/pair23-config2.jpg"
 },
 {
  "config1": "snapshot/pair24-config1.webp",
  "config2": "snapshot/pair24-config2.jpg"
 },
 {
  "config1": "snapshot/pair25-config1.webp",
  "config2": "snapshot/pair25-config2.jpg"
 },
 {
  "config1": "snapshot/pair26-config1.jpg",
  "config2": "snapshot/pair26-config2.jpg"
 },
 {
  "config1": "snapshot/pair27-config1.jpg",
  "config2": "snapshot/pair27-config2.jpg"
 },
 {
  "config1": "snapshot/pair28-config1.webp",
  "config2": "snapshot/pair28-config2.jpg"
 },
 {
  "config1": "snapshot/pair29-config1.webp",
  "config2": "snapshot/pair29-config2.jpg"
 },
 {
  "config1": "snapshot/pair30-config1.webp",
  "config2": "snapshot/pair30-config2.jpg"
 },
 {
  "config1": "snapshot/pair31-config1.webp",
  "config2": "snapshot/pair31-config2.jpg"
 },
 {
  "config1": "snapshot/pair32-config1.jpg",
  "config2": "snapshot/pair32-config2.jpg"
 },
 {
  "config1": "snapshot/pair33-config1.webp",
  "config2": "snapshot/pair33-config2.jpg"
 },
 {
  "config1": "snapshot/pair34-config1.webp",
  "config2": "snapshot/pair34-config2.jpg"
 },
 {
  "config1": "snapshot/pair35-config1.webp",
  "config2": "snapshot/pair35-config2.jpg"
 },
 {
  "config1": "snapshot/pair36-config1.webp",
  "config2": "snapshot/pair36-config2.jpg"
 },
 {
  "config1": "snapshot/pair37-config1.webp",
  "config2": "snapshot/pair37-config2.jpg"
 },
 {
  "config1": "snapshot/pair38-config1.webp",
  "config2": "snapshot/pair38-config2.jpg"
 },
 {
  "config1": "snapshot/pair39-config1.webp",
  "config2": "snapshot/pair39-config2.jpg"
 },
 {
  "config1": "snapshot/pair40-config1.webp",
  "config2": "snapshot/pair40-config2.jpg"
 },
 {
  "config1": "snapshot/pair41-config1.webp",
  "config2": "snapshot/pair41-config2.jpg"
 },
 {
  "config1": "snapshot/pair42-config1.webp",
  "config2": "snapshot/pair42-config2.jpg"
 }
];
